library("SuperExactTest")
d1<-sapply((as.data.frame(read.csv('listA.txt'))),as.character)
d2<-sapply((as.data.frame(read.csv('listB.txt'))),as.character)
d3<-sapply((as.data.frame(read.csv('listC.txt'))),as.character)
x <- list("MYC" = d1, "MTOR" = d2, "E2F" = d3)
res<-supertest(x, n=13000)
plot(res, sort.by="size")
plot(res, Layout="landscape", degree=2:4, sort.by="size", y.pos=c(0.025,0.95))
write.csv(summary(res)$Table, file="summary.table.csv", row.names=FALSE)
summary(res)
